services:
  - type: web
    name: spectral-ranking-backend
    env: docker
    dockerfilePath: Dockerfile.backend
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-5-nano
    disks:
      - name: jobs
        mountPath: /opt/render/project/src/jobs
        sizeGB: 1
      - name: agent-uploads
        mountPath: /opt/render/project/src/agent_uploads
        sizeGB: 1
    autoDeploy: true
    previews: true
    region: oregon
    startCommand: uvicorn code_app.backend.main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: spectral-ranking-frontend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.frontend.txt
    startCommand: python code_app/frontend/main.py
    envVars:
      - key: API_BASE_URL
        sync: false
    healthCheckPath: /dashboard
    autoDeploy: true
    previews: true
    region: oregon


